repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        exclude: tsconfig.json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint
        args: [--fix, --max-warnings, "0"]
        files: '\.[jt]sx?$'
        types: [file]
        additional_dependencies:
          - "eslint-config-next@13.5.4"
          - "eslint@8.51.0"
          - "next@13.5.4"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [css, javascript, ts, tsx]
